name: Origins-Mobs-Enhanced
version: 1.0.23
main: com.starshootercity.originsmobs.OriginsMobs
description: Origins-Reborn addon based on the Mob Origins mod by UltrusBot
api-version: '1.19'
author: cometcake575
depend:
  - Origins-Reborn-Enhanced
